remove: typing...
it not working and  giving err:

 TypeError: Cannot read properties of undefined (reading 'emit')

 and the server was disconnecting because of it